### PR TITLE
replace static to serverless

### PR DESCRIPTION
**Pull request by felix-lambert**
I think that serverless is more explicit (IMHO)

### CODE REVIEW

**Comment by nono** [comment]
There was also an option on _browserfull_.

@frankrousseau should we go on _serverless_ or _browserfull_?

**Comment by clochix** [comment]
I never heard of _browserfull_ and nobody seems to use it in this context, so I think **serverless** is definitively more understandable

**Comment by frankrousseau** [comment]
+1 for serverless

**Comment by nono** [comment]
Go for serverless then. Thanks @lemelon!

**Pull request merged**
